import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Marck_Script } from "next/font/google";
import "./globals.css";
import HeartsRain from "@/shared/heartRain/HeartRain";
import HeartEffect from "@/shared/heartEffect/HeartEffect";

const inter = Inter({
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Baymen Present",
  description: "Generated by create next app",
};
const marckScript = Marck_Script({
  subsets: ["latin", "cyrillic"],
  weight: "400",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${marckScript.className} ${inter.className}`}>
        <HeartsRain />
        {children}
        <HeartEffect />
      </body>
    </html>
  );
}
